new-feature: test CodeClimate

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,32 +23,32 @@ jobs:
           FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
         run: ./gradlew build
 
-#      - name: CodeClimate Analysis
-#        id: codeclimate_analysis
-#        run: |
-#          if ! command -v codeclimate &> /dev/null
-#          then
-#              echo "CodeClimate CLI not found. Installing..."
-#              curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz
-#              cd codeclimate-* && sudo make install
-#          fi
-#          codeclimate analyze --format=json > codeclimate_report.json
-#        env:
-#          CODECLIMATE_REPORT_PATH: codeclimate_report.json
-#
-#      - name: Get CodeClimate Analysis Link
-#        run: |
-#          if [ -f "${{ env.CODECLIMATE_REPORT_PATH }}" ]; then
-#            echo "CodeClimate analysis report generated. You can view the report at: https://codeclimate.com/dashboard/repositories/${{ github.repository }}/code_reviews"
-#          else
-#            echo "CodeClimate analysis failed or no report generated."
-#          fi
-
-
-      - name: Deploy to Firebase App Distribution
+      - name: CodeClimate Analysis
+        id: codeclimate_analysis
         run: |
-          npm install -g firebase-tools
-          TAG=$(echo ${GITHUB_REF/refs\/tags\//})
-          firebase appdistribution:distribute --app ${{ secrets.FIREBASE_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --release-notes "MeLi Mobile Candidate ($TAG)"
+          if ! command -v codeclimate &> /dev/null
+          then
+              echo "CodeClimate CLI not found. Installing..."
+              curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz
+              cd codeclimate-* && sudo make install
+          fi
+          codeclimate analyze --format=json > codeclimate_report.json
         env:
-          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+          CODECLIMATE_REPORT_PATH: codeclimate_report.json
+
+      - name: Get CodeClimate Analysis Link
+        run: |
+          if [ -f "${{ env.CODECLIMATE_REPORT_PATH }}" ]; then
+            echo "CodeClimate analysis report generated. You can view the report at: https://codeclimate.com/dashboard/repositories/${{ github.repository }}/code_reviews"
+          else
+            echo "CodeClimate analysis failed or no report generated."
+          fi
+
+
+#      - name: Deploy to Firebase App Distribution
+#        run: |
+#          npm install -g firebase-tools
+#          TAG=$(echo ${GITHUB_REF/refs\/tags\//})
+#          firebase appdistribution:distribute --app ${{ secrets.FIREBASE_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --release-notes "MeLi Mobile Candidate ($TAG)"
+#        env:
+#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
